id: P000480
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-16 15:42:10.332140
source_metadata:
  id: bdr:W1KG6094
  title: བོད་ཀྱི་གནའ་རྩོམ་གཅེས་བསྒྲིགས་
  author: ''
  volumes:
    ae5040d9ff584472930f3ff6bd842920:
      image_group_id: I1KG6265
      title: Volume 1 of bod kyi gna' rtsom gces bsgrigs
      volume_number: 1
      total_pages: 340
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
