id: I301A8356
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:23:15+00:00'
last_modified: '2022-06-10T06:32:19.552371+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6094
  title: བོད་ཀྱི་གནའ་རྩོམ་གཅེས་བསྒྲིགས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    6AFA:
      image_group_id: I1KG6265
      title: Volume 1 of bod kyi gna' rtsom gces bsgrigs
      total_pages: 340
      order: 1
      base_file: 6AFA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
